# add the following to _config.yml file
title: Noah Nyland
show_downloads: true
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # or auto if you want it to switch with your system settings.
 # add this line to the plugins list if you already have one # add this line to the plugins list if you already have one
